{% set name = "coredns" %}
{% set version = "1.1.2" %}

{% set sha256 = "8715d41d43adacd3cf9db0a9f6599de4d3024a1808a8029bf4c0d0931397ce35" %}
{% set sha256_win64 = "5e70498329f15d10bc4ccfdece5a4be8510ade7c5732cc358b7959751a00c09a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coredns/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: {{ sha256 }}  # [not win]

  url: https://github.com/coredns/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_windows_amd64.tgz  # [win]
  fn: {{ name }}-{{ version }}.tgz  # [win]
  sha256: {{ sha256_win64 }}  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - go 1.9.*  # [not win]
    - make  # [not win]
    - toolchain  # [not win]

test:
  commands:
    - coredns --version

    # Ugly hack because etcd&etcdclt are not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coredns.io/
  license: Apache-2.0
  license_family: Apache
  summary: CoreDNS is a DNS server written in Go that chains plugins
  doc_url: https://coredns.io/manual/toc/
  dev_url: https://github.com/coredns/coredns

extra:
  recipe-maintainers:
    - sodre
