{% set name = "coredns" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coredns/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 6f616382acea534589f6b98b5d59b0c0504053d4b4d4aeb6516f14c11fcb7f49  # [not win]

  url: https://github.com/coredns/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_windows_amd64.tgz  # [win]
  fn: {{ name }}-{{ version }}.tgz  # [win]
  sha256: b894cffe41baf17addc1dbf290cc9cd6f82d555beca3286670f7112d4797780a  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - make  # [not win]
    - go 1.9.*  # [not win]

test:
  commands:
    - coredns --version

    # Ugly hack because coredns is not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coredns.io/
  license: Apache-2.0
  license_family: Apache
  summary: CoreDNS is a DNS server written in Go that chains plugins
  doc_url: https://coredns.io/manual/toc/
  dev_url: https://github.com/coredns/coredns

extra:
  recipe-maintainers:
    - sodre
