{% set name = "coredns" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coredns/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: ef7f8536b63dd23cff297667da750f8d4c0c9dc80087b6256dc7333c4359665e  # [not win]

  url: https://github.com/coredns/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_windows_amd64.tgz  # [win]
  fn: {{ name }}-{{ version }}.tgz  # [win]
  sha256: 731941e87ea070c5804dfe7dfe8204c6ab555889f6b87533ab3e1e12903db83e  # [win]

build:
  skip: True  # [win32]
  number: 1

requirements:
  build:
    - make  # [not win]
    - go 1.9.*  # [not win]

test:
  commands:
    - coredns --version

    # Ugly hack because coredns is not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coredns.io/
  license: Apache-2.0
  license_family: Apache
  summary: CoreDNS is a DNS server written in Go that chains plugins
  doc_url: https://coredns.io/manual/toc/
  dev_url: https://github.com/coredns/coredns

extra:
  recipe-maintainers:
    - sodre
