{% set name = "coredns" %}
{% set go_pkg_name = "github.com/coredns/" + name %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/{{ go_pkg_name }}  # [not win]
    git_url: https://{{ go_pkg_name }}  # [not win]
    git_rev: v{{ version }}  # [not win]

    url: https://github.com/coredns/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_windows_amd64.tgz  # [win]
    sha256: 7c793b042cf0738340a624e5784be32909ceaa58fee074d732c8aeb598df6376  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - make  # [not win]
    - {{ compiler('go') }}  # [not win]

test:
  commands:
    - coredns --version

about:
  home: https://coredns.io/
  license: Apache 2.0
  license_family: Apache
  summary: CoreDNS is a DNS server written in Go that chains plugins
  doc_url: https://coredns.io/manual/toc/
  dev_url: https://github.com/coredns/coredns

extra:
  recipe-maintainers:
    - sodre
