travis:
  secure:
    BINSTAR_TOKEN: zJuQSSiJXRdc8HVX7ZzEWwQnggEmHzTEX01Hk7xYfD7IwdcWYZynwbymIJGiNo48IKo/hqRdawjfg5jq15vM+Y8eXfS9phfx/poSvoqAxz0Qowp2K5HzeVVO2V3c86Cuh9AflEeEql8aWAFztyLDX5JnUJi4Mn/SendT8PLANpW/GZ4TB8+1o82y1tgnFGNZPPLUeR2K0TlambhSOUn567AOd8Csp/JK5GTo0LTw5tW/ZAYp052v9RRdaslmExpWKOfTp8Sq5cnxUhqunEzfBbD0jPaWygMlJxrZhWnZhIM4HQ6Qw6B8g2vscTvrwY72a1DZa1SmpvmUzb8iZfw9HI093zBLN6weJBRg0nz82btpbKm9uL2U32BJqWFf83mOZVI8VEkvnxRbg71wM9AzXOwVrk3y8QMpFxoFQ0fxy2p/j2dqAvOh8fpxRpuYbB/JAXjQSvjKkPUdAnMfIayAcM7NL7GP+jiEuTd9hTdVvdYr/dLapYXxWqA7GSfyBn5sW4quHJqZkHtFRXOVz83Rms4RbbXYoddJcxcds5MAxJjj7/RW8ZBjg6Ss29ND2dwywBSodHEwvyi8QeUCk8r9vC0O8qvlxyXqi76RehWc1RgqlAQRqRBWwnPG5dLFJlIF8H5F6jZsiTUVARFxMIBKNLO4SKLIrBqS0eSWXryLtjY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
