travis:
  secure:
    BINSTAR_TOKEN: gtml1pYvS5itcPq6ao4W17JVK0N2c6vZ/Zptd78WBq68M07gTEInWdYqnvJ0cDdN4HBcg+R6cUPrF9DUtBHecOKSR4tuKqHlUZY4YUlKjJjUTYrXn5KnX5arthvl/wjt2+UiCi2MfRXpixLVoTnHyvDypAO10mD8LvmzQbUBVfPtpmEulYQJvZopIsXOVwg12cQCrJsl8arnnbh+vEANS8UtFMqH7Hwh969yMWjBtpacueJlNoDD0vOCprD4+J0kbN4fYjyAxyDsPXjIeBh0Bja86nh80NflYz8XWrkp3061KsHpvVb8UJuJl+Eg+3LzNScq7sb4KVT5ZVh4nOHGWPBF4uEXFLkysTLo9rE+sHZK6m+2zxcBH845pBfj8gkzmU+NQezzTq74bFKC1w8aO/+Xxr2qMBl0jnjOhpPQy598UDhJEyC2jSmFOeu1Fs+UwQ1xf3nyNFuoGjsIMFHVXqTAA/AHbA4/AMXs69C45BRoEOZKHwBI1Li3c0Q2pyO1ZHxtjH4VW8KfjyJuyOtyFb8PKH9xVuWquUIXxyuoB/4W9Pu3NLiSYTexgl9dhtvkq4jB4itMYEshdOgk0em0RJch0xK93D1vWmoKnQaBTkHi4lzPl2CynEEVLIfTac8/WC81zdR7UrcEf38Em0rfxNurWUAwq/0K5yj9A5bmH+g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
